#theme: minima
sass:
  custom_css: assets/css/style.scss  # หรือใช้ .css หากคุณใช้ไฟล์ CSS แทน SCSS
#theme: jekyll-theme-minimal # ใช้ธีม minimal
url: "https://anniemark2522.github.io"
baseurl: ""
color_scheme: "pink"  # ให้ใช้สีชมพูในการแสดงผล



title: "Klittima's Cute GitHub Page"  # ชื่อเว็บไซต์
description: "A cute minimal theme page"  # คำอธิบาย
theme: "indigo"  # ใช้ธีม Cute Minimal (Indigo)

